---
- hosts: all
#- name: Instalar (o actualizar a) la ultima version HTOP
#  package: name=htop state=latest

# This uses a variable as this changes per distribution.
# # Ubuntu: apache2
# # CentOS: httpd
# - name: remove the apache package
#   package : name={{apache}} state=absent
#

#
#when: ansible_distribution == 'CentOS' and ansible_distribution_version == '6.4'
#
#when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise'
#
#when: ansible_distribution == 'Debian' and ansible_distribution_version == '7'
#
#when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int >= 5


  tasks:
  - apt: name=$item state=latest
    with_items:
     - ntp
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - yum: name=$item state=latest
    with_items:
     - ntp
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - dnf: name=$item state=latest
    with_items:
    - ntp
    when: ansible_distribution == 'Fedora'

  - service: name=ntpd state=started enabled=yes

