---
- hosts: local
#  remote_user: dmoreno
#  sudo: yes
  tasks:
     - name: Crea directorio de descargas
       file: path=/tmp/descargas state=directory mode=0755

     - name: Descarga Logo de URL
       get_url: url=http://blog.itlinux.cl/images/logo_mini.png dest=/tmp/descargas/logo_mini.png

