# This playbook update all Fedora hosts.
#
# Copyright (c) 2013-2017 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- hosts: all
  user: deibis
  become: yes

  tasks:
    - name: upgrade all packages
      raw: /usr/bin/dnf -y upgrade
