- hosts: all
  become: yes
  gather_facts: yes #IMPORTANT
  remote_user: root
  
  tasks:
      - name: Instalación de Postgres
        package: name={{ item }} state=latest
        with_items:
        - postgresql96*
        - postgresql96-server
        - postgis-utils
        - postgis24*
        - pg_top96
<<<<<<< HEAD
        igonore_errors: true
=======
>>>>>>> origin

      - name: Inicializar Base de Datos
        shell: /usr/pgsql-9.6/bin/postgresql96-setup initdb
        #postgresql-setup initdb



#      - name: Enable/Inicializar Postgres
#        service: 
#                name: postgresql-9.6 
#                enabled: yes 
#                state: started









