# This playbook install flatpak CentOS hosts.
#
# Copyright (c) 2018 Deibis Moreno <deimo72@gmail.com>
#
# Licensed under CC BY 3.0. All rights reserved.
#

---
- hosts: all
  become: yes
  gather_facts: False
  remote_user: root
  tasks:

      - name: Instalar Python2 
        raw: yum install -y python2 python-simplejson
      - name: Enable Flathub repository
        become: yes
        command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      #- name: Install Fractal
      #  become: yes
      #  command: flatpak install --assumeyes flathub org.gnome.Fractal
      - name: Install Spotify
        become: yes
        command: flatpak install --assumeyes flathub com.spotify.Client
      - name: Install Visual Studio Code
        become: yes
        command: flatpak install --assumeyes flathub com.visualstudio.code
      - name: Install Atom
        become: yes
        command: flatpak install --assumeyes flathub io.atom.Atom
