---
language: python
python: "2.7.13"
sudo: required
language: python
services:
  - docker
install:
  - pip install ansible==2.3.1.0
  - pip install molecule
  - pip install docker
script:
  - molecule test --driver docker

notifications:
webhooks: https://galaxy.ansible.com/api/v1/notifications/
