---
- name: 1.Check if EPEL repo is already configured.
  stat: path={{ pg_repofile_path }}
  register: pg_repofile_result
     
- name: 2.Install Postgres repo.
  yum:
      name: "{{ pg_repo_url }}"
      state: present
  register: result
  when: not pg_repofile_result.stat.exists
                    
#- name: 3.Import EPEL GPG key.
#  rpm_key:
#    key: "{{ epel_repo_gpg_key_url }}"
#    state: present
#  when: not epel_repofile_result.stat.exists
